#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(non_camel_case_types)]
pub enum TaxonKind {
	// Languages Scripts and General Categories
	ROMAN,
	LATIN,
	CYRILLIC,
	HELLENIC,
	SHAVIAN,
	DESERET,
	INTERNATIONAL_PHONETIC_ALPHABET,
	GERMANIC_RUNES,
	CIRTH_RUNIC,
	GLAGOLITIC,
	MANICHAEAN,
	ANCIENT_NORTH_ARABIC,
	ANCIENT_SOUTH_ARABIC,
	OLD_PERSIAN,

	// Specific Taxons
	LIGATURE,
	DIGRAPH,
	ACCENTED,
	NUMERAL,

	// Script Specific
	// Latin
	HELLENIC_DESCENDENT,

	// Germanic Runes
	ELDER_FUTHARK,
	ANGLO_SAXON_FUTHORK,
	YOUNGER_FUTHARK,
	ALMANAC_RUNES,
	LATER_YOUNGER_FUTHARK,
	MEDIEVAL_RUNES,

	// Other
	ALCHEMICAL_SYMBOL,
	ASTRONOMICAL_SYMBOL,
	ASTROLOGICAL_SYMBOL,

	ZHONG_GUO,
	DAO,
	YI_JING,
	TAI_XUAN_JING,
	MAJIANG,

	NONE,
}
